version: '3'

services:
  tests:
    image: node:fermium-alpine
    command: sh -c "npm install && npm run test"
    volumes:
      - ./:/app
    working_dir: /app

  app:
    image: node:fermium-alpine
    depends_on:
      - tests
    command: npm run start
    ports:
      - "3333:3000"
    volumes:
      - ./:/app
    working_dir: /app

